version: '3'

tasks:
  default:
    cmds:
      - task --list
    silent: true

  install:
    desc: Install dependencies
    cmds:
      - pnpm install

  dev:
    desc: Run Next.js development server
    cmds:
      - pnpm run dev

  build:
    desc: Build production bundle
    cmds:
      - pnpm run build

  typecheck:
    desc: Run TypeScript type checking
    cmds:
      - pnpm run typecheck

  lint:
    desc: Run quality checks (eslint, knip, jscpd, ast-grep)
    cmds:
      - pnpm run lint
      - pnpm run knip
      - pnpm run jscpd
      - pnpm run ast-grep

  report:
    desc: Generate a full quality report
    cmds:
      - mkdir -p report
      - pnpm run jscpd > report/jscpd.txt
      - pnpm run knip > report/knip.txt
      - pnpm run ast-grep > report/ast-grep.txt
